### ISSUE TITLE
Post https://mbus:mbus-password@0.0.0.0:6868/agent: Forbidden port

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry/bosh-init#113]
Hi,

I got the following error during the bosh init create VM.

> Command 'deploy' failed:
>   Deploying:
>     Creating instance 'bosh/0':
>       Waiting until instance is ready:
>         Sending ping to the agent:
>           Performing request to agent endpoint 'https://mbus:mbus-password@139.25.25.219::6868/agent':
>             Performing POST request:
>               Post https://mbus:mbus-password@139.25.25.219::6868/agent: Forbidden port

SSH is possible to the maschin.
Also a nc

>  nc -zv 139.25.25.219 6868
> Connection to 139.25.25.219 6868 port [tcp/*] succeeded!

but wget provides a 401

> https://mbus:_password_@139.25.25.219:6868/agent
> Connecting to 139.25.25.219:6868... connected.
> WARNING: cannot verify 139.25.25.219's certificate, issued by ‘/C=US/O=Pivotal/CN=localhost’:
>   Self-signed certificate encountered.
>     WARNING: certificate common name ‘localhost’ doesn't match requested host name ‘139.25.25.219’.
> HTTP request sent, awaiting response... 401 Unauthorized
> Reusing existing connection to 139.25.25.219:6868.
> HTTP request sent, awaiting response... 404 Not Found
> 2016-10-14 08:00:41 ERROR 404: Not Found.

Here are my bosh.yml

```
---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.15
  sha1: f4cf3579bfac994cd3bde4a9d8cbee3ad189c8b2
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=27
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3263.7
    sha1: 079fd87e0e707cfa09bad781086983c25a605962
  cloud_properties:
    instance_type: m1.xlarge

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24 # <--- Replace with a private subnet CIDR
    gateway: 10.0.0.1 # <--- Replace with a private subnet's gateway
    dns: [10.0.0.2] # <--- Replace with your DNS
    cloud_properties: {net_id: 99828b4e-cb2b-45bf-97e2-852388bc16c0} # <--- # Replace with private network UUID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.101] # <--- Replace with a private IP
    default: [dns, gateway]
  - name: public
    static_ips: [139.25.25.219] # <--- Replace with a floating IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 10.0.0.101 # <--- Replace with a private IP
      host: 10.0.0.101 # <--- Replace with a private IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 10.0.0.101 # <--- Replace with a private IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 3
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    openstack: &openstack
      #auth_url: https://10.10.0.10:35357/v3/tokens # <--- Replace with OpenStack Identity API endpoint
      auth_url: https://10.10.0.10:5000/v2.0/tokens
      project: CF_Diego # <--- Replace with OpenStack project name
      tenant: CF_Diego
      domain: default # <--- Replace with OpenStack domain name
      username: STUSER # <--- Replace with OpenStack username
      api_key: MYPASS  # <--- Replace with OpenStack password
      default_key_name: bosh-manual-key
      default_security_groups: [bosh, Security]
      connection_options: # all connection options that are supported by Excon
       ssl_verify_peer: false # Boolean

    agent: {mbus: "nats://nats:nats-password@139.25.25.219:4222"} # <--- Replace with a private IP

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: 139.25.25.219 # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: ../bosh-manual-key # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@139.25.25.219:6868" # <--- Replace with a floating IP

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp

```
