### ISSUE TITLE
 Error filling in template 'director.yml.erb.erb' (line 518: Could not find cloud plugin)

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/bosh-init#126]
Hi ,

I am trying to deploy CF on Openstack. 
I have the following in microbosh.yml
```yaml
---
name: microbosh
logging:
  level: DEBUG
network:
  type: dynamic
  vip: myfloatingip
  cloud_properties:
    net_id: 3a374103-4b4a-49aa-b2e7-d113c39c3
resources:
  persistent_disk: 16384
  cloud_properties:
    instance_type: m1.large
cloud:
  plugin: openstack
  properties:
   openstack:
      auth_url: https://keystoneIp:5000/v2.0
      tenant: myproject
      username: myusername
      api_key: mypassword
      default_key_name: my-keypair-name
      private_key: /path/to/my-keypair.pem
      default_security_groups: [bosh,CF]
      proxy_uri: http://proxyip:port
apply_spec:
  properties:
     director: {max_threads: 3}
     hm: {resurrector_enabled: true}
     ntp: [x.x.x.x]
```
When I execute  

> bosh micro deploy bosh-stemcell-3263.14-openstack-kvm-ubuntu-trusty-go_agent.tgz

I get the following error 
```
 /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bosh-director-core-1.3262.24.0/lib/bosh/director/core/templates/job_instance_renderer.rb:31:in `render': Unable to render jobs for instance group 'micro_openstack'. Errors are: (RuntimeError)
   - Unable to render templates for job 'director'. Errors are:
     - Error filling in template 'director.yml.erb.erb' (line 518: Could not find cloud plugin)
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bosh_cli_plugin_micro-1.3262.24.0/lib/bosh/deployer/microbosh_job_instance.rb:37:in `render_templates'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bosh_cli_plugin_micro-`  
```
detailed log : 
https://gist.github.com/gowriln/78c62e86082360ea93acd532770389c9

Can anyone help me with this ?
