### ISSUE TITLE
Post https://nats:nats@184.72.235.129:6868/agent: dial tcp 184.72.235.129:6868: connection refused

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#27]
I'm trying to upgrade https://github.com/cloudfoundry-community/bosh-init-redis to new `bosh-init deploy manifest.yml` and am getting a connection error that I didn't get before. Are there any new manifest.yml attributes I need?

I've confirmed that port 6868 is still open to all clients on the security group.

The inputs are all latest releases & aws stemcell & HEAD for bosh-init itself.

```
Deployment manifest: '/tmp/build/src/redis.yml'
Deployment state: '/tmp/build/src/redis-state.json'

Started validating
  Validating deployment manifest... Finished (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating release 'redis'... Finished (00:00:00)
  Validating jobs... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
Finished validating (00:00:00)

Started installing CPI
  Compiling package 'ruby_aws_cpi/7903f3a543e8ab35fd980a0ca74f9151282d56b2'... Finished (00:02:24)
  Compiling package 'bosh_aws_cpi/2bb22c5a553350eed303a5382d4d557798d48914'... Finished (00:01:53)
  Rendering job templates... Finished (00:00:00)
  Installing packages... Finished (00:00:02)
  Installing job 'cpi'... Finished (00:00:00)
Finished installing CPI (00:04:20)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-aws-xen-ubuntu-trusty-go_agent/2941'... Finished (00:00:10)

Started deploying
  Creating VM for instance 'redis/0' from stemcell 'ami-fe818796 light'... Finished (00:00:45)
  Waiting for the agent on VM 'i-1ef891e3' to be ready... Failed (00:10:00)
Failed deploying (00:10:45)

Command 'deploy' failed:
  Deploying:
    Creating instance 'redis/0':
      Waiting until instance is ready:
        Sending ping to the agent:
          Performing request to agent endpoint 'https://nats:nats@184.72.235.129:6868/agent':
            Performing POST request:
              Post https://nats:nats@184.72.235.129:6868/agent: dial tcp 184.72.235.129:6868: connection refused
```

For manifest.yml

```yaml
---
name: redis

releases:
- name: bosh-aws-cpi
  url: file://release-cpi/release.tgz
- name: redis
  url: file://release-redis/release.tgz

resource_pools:
- name: default
  network: default
  stemcell:
    url: file://stemcell/stemcell.tgz
  cloud_properties:
    instance_type: m3.medium
    availability_zone: us-east-1c

jobs:
- name: redis
  instances: 1
  persistent_disk: 10240
  resource_pool: default
  templates:
  - {name: redis, release: redis}
  networks:
  - name: vip
    static_ips: [184.72.235.129]
  - name: default

  properties:
    redis:
      port: 6379

networks:
- name: default
  type: dynamic
- name: vip
  type: vip

cloud_provider:
  template: {name: cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: 184.72.235.129
    port: 22
    user: vcap
    private_key: aws-private-key/private-key.pem

  registry: &registry
    username: admin
    password: admin
    port: 6901
    host: localhost

  # Tells bosh-micro how to contact remote agent
  mbus: https://nats:nats@184.72.235.129:6868

  properties:
    aws:
      access_key_id: XXX
      secret_access_key: YYY
      default_key_name: sw-bosh-us-east-1
      default_security_groups: [redis-server]
      region: us-east-1

    # Tells CPI how agent should listen for requests
    agent: {mbus: "https://nats:nats@0.0.0.0:6868"}

    registry: *registry

    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache

    ntp: [0.north-america.pool.ntp.org]
```
