### ISSUE TITLE
cloud_provider.ssh_tunnel.private_key cannot be relative to ~/.ssh

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#4]
The following worked:

```yaml
cloud_provider:
  release: bosh-aws-cpi
  ssh_tunnel:
    host: 10.10.1.4
    port: 22
    user: vcap
    private_key: /home/ubuntu/.ssh/sw-bosh-us-west-2.pem
```

But the following fails to find the key file:

```yaml
cloud_provider:
  release: bosh-aws-cpi
  ssh_tunnel:
    host: 10.10.1.4
    port: 22
    user: vcap
    private_key: ~/.ssh/sw-bosh-us-west-2.pem
```
