### ISSUE TITLE
Stuck in creating VM

### ISSUE THREAD

**Issue by LaynePeng** [cloudfoundry/bosh-init#42]
Hi, 

My environment is OpenStack. And I use bosh-init to deploy the micro-bosh, then use the micro-bosh to deploy releases. Everything fine until today.  

However, I suddenly met the problem of cannot create VM . Actually, the VM has been created in OpenStack, but it seems cannot communicated with BOSH director. Then I SSH to the VM create, find the following logs:

```
2015-08-26_15:41:35.51067 [settingsService] 2015/08/26 15:41:35 ERROR - Failed reading settings from file Opening file /var/vcap/bosh/settings.json: open /var/vcap/bosh/settings.json: no such file or directory

**Comment by cppforlife** [comment]
That may not be the root problem. Please search for 'Starting agent' in the agent log and include here few surrounding lines.

**Comment by LaynePeng** [comment]
Hi, thanks for quick response. I just check the Starting part, but found nothing...

```
2015-08-26_16:27:21.09091 [main] 2015/08/26 16:27:21 DEBUG - Starting agent
2015-08-26_16:27:21.09152 [File System] 2015/08/26 16:27:21 DEBUG - Reading file /var/vcap/bosh/agent.json
2015-08-26_16:27:21.09744 [File System] 2015/08/26 16:27:21 DEBUG - Read content
2015-08-26_16:27:21.09745 ********************
2015-08-26_16:27:21.09746 {
2015-08-26_16:27:21.09746   "Platform": {
2015-08-26_16:27:21.09746     "Linux": {
2015-08-26_16:27:21.09747       "CreatePartitionIfNoEphemeralDisk": true,
2015-08-26_16:27:21.09747       "DevicePathResolutionType": "virtio"
2015-08-26_16:27:21.09747     }
2015-08-26_16:27:21.09748   },
2015-08-26_16:27:21.09748   "Infrastructure": {
2015-08-26_16:27:21.09748     "NetworkingType": "dhcp",
2015-08-26_16:27:21.09748
2015-08-26_16:27:21.09749     "Settings": {
2015-08-26_16:27:21.09749       "Sources": [
2015-08-26_16:27:21.09749         {
2015-08-26_16:27:21.09749           "Type": "ConfigDrive",
2015-08-26_16:27:21.09750           "DiskPaths": [
2015-08-26_16:27:21.09750             "/dev/disk/by-label/CONFIG-2",
2015-08-26_16:27:21.09750             "/dev/disk/by-label/config-2"
2015-08-26_16:27:21.09751           ],
2015-08-26_16:27:21.09751           "MetaDataPath": "ec2/latest/meta-data.json",
2015-08-26_16:27:21.09751           "UserDataPath": "ec2/latest/user-data"
2015-08-26_16:27:21.09752         },
2015-08-26_16:27:21.09752         {
2015-08-26_16:27:21.09752           "Type": "HTTP",
2015-08-26_16:27:21.09752           "URI": "http://169.254.169.254"
2015-08-26_16:27:21.09753         }
2015-08-26_16:27:21.09753       ],
2015-08-26_16:27:21.09753
2015-08-26_16:27:21.09754       "UseServerName": true,
2015-08-26_16:27:21.09754       "UseRegistry": true
2015-08-26_16:27:21.09754     }
2015-08-26_16:27:21.09754   }
2015-08-26_16:27:21.09755 }
2015-08-26_16:27:21.09755
2015-08-26_16:27:21.09755 ********************
2015-08-26_16:27:21.09756 [Cmd Runner] 2015/08/26 16:27:21 DEBUG - Running command: bosh-agent-rc
2015-08-26_16:27:21.10418 [Cmd Runner] 2015/08/26 16:27:21 DEBUG - Stdout:
2015-08-26_16:27:21.10419 [Cmd Runner] 2015/08/26 16:27:21 DEBUG - Stderr:
2015-08-26_16:27:21.10419 [Cmd Runner] 2015/08/26 16:27:21 DEBUG - Successful: true (0)
2015-08-26_16:27:21.10420 [ConfigDriveMetadataService] 2015/08/26 16:27:21 DEBUG - Loading config drive metadata service
2015-08-26_16:27:21.10420 [File System] 2015/08/26 16:27:21 DEBUG - Checking if file exists /dev/disk/by-label/CONFIG-2
2015-08-26_16:27:21.10420 [ConfigDriveMetadataService] 2015/08/26 16:27:21 WARN - Failed to load config from /dev/disk/by-label/CONFIG-2 - Reading files on config drive: Failed to get file contents, disk path '/dev/disk/by-label/CONFIG-2' does not exist

...

2015-08-26_16:27:21.16761 [Cmd Runner] 2015/08/26 16:27:21 DEBUG - Successful: false (1)
2015-08-26_16:27:21.16767 [UbuntuNetManager] 2015/08/26 16:27:21 ERROR - Ignoring failure calling 'pkill dhclient': Running command: 'pkill dhclient', stdout: '', stderr: '': exit status 1
2015-08-26_16:27:21.16769 [File System] 2015/08/26 16:27:21 DEBUG - Glob '/sys/class/net/*'
2015-08-26_16:27:21.17028 [File System] 2015/08/26 16:27:21 DEBUG - Checking if file exists /sys/class/net/eth0/device
2015-08-26_16:27:21.17034 [File System] 2015/08/26 16:27:21 DEBUG - Reading file /sys/class/net/eth0/address

**Comment by bosh-init-concourse** [comment]
Are you using config-drive or http metadata?

**Comment by LaynePeng** [comment]
Do you mean the OpenStack metadata service? I am not using it in this BOSH release. But we enable it in our OpenStack environment.

**Comment by bosh-init-concourse** [comment]
I meant is your CPI configured to use config-drive or http metadata. Can
you paste in more debug output? It seems that agent does not see
config-drive (Reading files on config drive: Failed to get file contents,
disk path '/dev/disk/by-label/CONFIG-2' does not exist) and will try to
look at "http://169.254.169.254" next. That probably fails too.

Btw which version of director and stemcells you are using?

**Comment by LaynePeng** [comment]
BOSH director version: 1.3026.0
Stellcell: bosh-openstack-kvm-ubuntu-trusty-go_agent/3029

I didn't see my CPI configured to use config-drive, the following is my CPI config:

```
cloud:
  plugin: openstack
  properties:
    openstack:
      auth_url: http://10.10.132.20:5000/v2.0
      username: xxx
      api_key: xxx
      tenant: cloudfoundry
      endpoint_type: publicURL
      state_timeout: 300
      stemcell_public_visibility: false
      boot_from_volume: false
      default_key_name: bosh-kilo
      default_security_groups: ["bosh"]
      wait_resource_poll_interval: 5
      ignore_server_availability_zone: false

    registry:
      endpoint: http://10.0.0.50:25777
      user: admin
      password: admin
      address: 10.0.0.50
      http:
        port: 25777
        user: admin
        password: admin

    agent:
      ntp: [10.32.97.145]

      blobstore:
        provider: dav
        options:
          endpoint: 'http://10.0.0.50:25250'
          user: agent
          password: agent-password
```
