### ISSUE TITLE
Bind multiple networks to BOSH VM

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry/bosh-init#61]
I try to bind multiple networks to BOSH VM.
For example following manifest.

```yaml
networks:
- name: network1
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: &dns
    - 8.8.8.8
    - 8.8.4.4
    cloud_properties: {net_id: aaaaa-aaaaa}
- name: network2
  type: dynamic
  subnets:
  - range: 10.1.0.0/24
    gateway: 10.1.0.1
    dns: *dns
    cloud_properties: {net_id: bbbbb-bbbbb}

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: network1
    static_ips: [10.0.0.10]
    default: [dns, gateway]
  - name: network2
```

But can not deploy and bosh-init outputs following error log.
```
2015-12-18_02:24:24.53484 [main] 2015/12/18 02:24:24 ERROR - App setup Running bootstrap: Setting up networking: Computing network configuration: Creating interface configurations: Number of network settings '2' is greater than the number
 of network devices '1'
```
