### ISSUE TITLE
how do i make ssh_tunnel connection timeout longer?

### ISSUE THREAD

**Issue by hanzhefeng** [cloudfoundry/bosh-init#67]
my CPI injects the public key to vm instance very slow. the bosh deploy ssh_tunnel connection always gets timeout before the public key been injected.

is there anyway i can control the timeout value for both "ConnectionRefusedTimeout" and "AuthFailureTimeout" in file /bosh-init/bosh-init-master/deployment/sshtunnel/ssh_tunnel.go?

Thanks!

**Comment by cppforlife** [comment]
Feel free to file a PR that adds custom options to bosh-init under cloud_provider e.g.

```
cloud_provider:
  ssh_tunnel:
    connection_refused_timeout: x
    auth_failure_timeout: x
```
