### ISSUE TITLE
Template Rendering fails if `jobs.X.properties` is empty

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-init#71]
If `jobs.X.properties` is empty, and properties are specified as global properties at `properties`, all templates fail to render, with the error 

```erb-render.rb:11:in `merge!': no implicit conversion of nil into Hash (TypeError)```

Adding an empty map to the job-specific properties key resolves this. This key is not required for traditional bosh deploys, so it feels like this should be allowed in bosh-init as well.

Failing manifest excerpt:
```
jobs:
- instances: 1
  name: bosh
  networks:
  - name: default
    static_ips:
    - 10.10.10.10
  persistent_disk_pool: bosh
  resource_pool: bosh
  templates:
  - name: postgres
    release: bosh
  - name: nats
    release: bosh
  - name: redis
    release: bosh
  - name: blobstore
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: vsphere_cpi
    release: bosh-vsphere-cpi
properties:
  agent:
    mbus: nats://nats:nats-password@10.10.10.10:4222
  ... (remaining properties omitted for brevity)
```
Working manifest excerpt:
```
jobs:
- instances: 1
  name: bosh
  networks:
  - name: default
    static_ips:
    - 10.10.10.10
  persistent_disk_pool: bosh
  resource_pool: bosh
  templates:
  - name: postgres
    release: bosh
  - name: nats
    release: bosh
  - name: redis
    release: bosh
  - name: blobstore
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: vsphere_cpi
    release: bosh-vsphere-cpi
  properties: {}
properties:
  agent:
    mbus: nats://nats:nats-password@10.10.10.10:4222
  ... (remaining properties omitted for brevity)
```
