### ISSUE TITLE
bosh-init >=0.0.87 panics with dynamic networks

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/bosh-init#77]
Steps to reproduce:
Use a deployment manifest with dynamic network:

```
---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=256
  sha1: 71701e862c0f4862cb77719d5f3e4f7451da355c
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=24
  sha1: 6621ee1326e7136d9dbebacd1158d101618dc719

networks:
  - name: private
    type: dynamic
    dns: ["8.8.8.8"]
    cloud_properties:
      net_id: <redacted>
      security_groups: ["bosh"]
  - name: public
    type: vip

resource_pools:
  - name: default
    network: private
    stemcell:
      url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3232
      sha1: 285193c8a6e8a001d0308e84b052276cb9677f79
    cloud_properties:
      instance_type: m1.medium

disk_pools:
  - name: default
    disk_size: 25_000

jobs:
  - name: bosh
    templates:
      - {name: nats, release: bosh}
      - {name: postgres, release: bosh}
      - {name: blobstore, release: bosh}
      - {name: director, release: bosh}
      - {name: health_monitor, release: bosh}
      - {name: registry, release: bosh}
      - {name: powerdns, release: bosh}
      - {name: openstack_cpi, release: bosh-openstack-cpi}

    instances: 1
    resource_pool: default
    persistent_disk_pool: default

    networks:
      - name: private
        default: [dns, gateway]
      - name: public
        static_ips: [192.168.138.152]

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: password

      postgres: &db
        host: 127.0.0.1
        user: postgres
        password: password
        database: bosh
        adapter: postgres

      # Tells the Director/agents how to contact registry
      registry:
        address: 192.168.138.152
        host: 192.168.138.152
        db: *db
        http: {user: admin, password: password, port: 25777}
        username: admin
        password: password
        port: 25777
        endpoint: http://admin:password@192.168.138.152:25777

      # Tells the Director/agents how to contact blobstore
      blobstore:
        address: 192.168.138.152
        port: 25250
        provider: dav
        director: {user: director, password: password}
        agent: {user: agent, password: password}

      director:
        address: 127.0.0.1
        name: micro
        db: *db
        cpi_job: openstack_cpi
        user_management:
          provider: local
          local:
            users:
              - {name: admin, password: password}

      hm:
        http: {user: hm, password: password}
        director_account: {user: admin, password: password}

      dns:
        address: 127.0.0.1
        db: *db

      openstack: &openstack
        auth_url: <redacted> # <--- Replace with OpenStack Identity API endpoint
        project: <redacted> # <--- Replace with OpenStack tenant name
        domain: Default
        username: <redacted> # <--- Replace with OpenStack username
        api_key: <redacted> # <--- Replace with OpenStack password
        default_key_name: bosh
        default_security_groups: [bosh]
        human_readable_vm_names: true
        connection_options:
          ssl_verify_peer: false
      # Tells agents how to contact nats
      agent: {mbus: "nats://nats:password@192.168.138.152:4222"}

      ntp: &ntp
        - 0.north-america.pool.ntp.org
        - 1.north-america.pool.ntp.org

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  # Tells bosh-micro how to SSH into deployed VM
  ssh_tunnel:
    host: 192.168.138.152
    port: 22
    user: vcap
    private_key: bosh.pem

  # Tells bosh-micro how to contact remote agent
  mbus: https://mbus-user:password@192.168.138.152:6868

  properties:
    openstack: *openstack

    # Tells CPI how agent should listen for requests
    agent: {mbus: "https://mbus-user:password@0.0.0.0:6868"}

    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache

    ntp: *ntp
```

It looks like bosh-init is deploying successfully... 
```
Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-openstack-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'ruby_openstack_cpi/7bb6f6bfb6014a9630ebb5686fd2f1ff4e0289ae'... Finished (00:01:49)
  Compiling package 'bosh_openstack_cpi/3a41d45536a57cea65bf8a114cfcd1f0a035639e'... Finished (00:01:47)
  Installing packages... Finished (00:00:33)
  Rendering job templates... Finished (00:00:00)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:04:10)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-openstack-kvm-ubuntu-trusty-go_agent/3232'... Finished (00:11:24)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell '901c3d73-2be8-4359-8d35-7c10a53043f0'... Finished (00:00:57)
  Waiting for the agent on VM '05b15c2f-21d9-41e8-a5a2-b48a6347dcf2' to be ready... Finished (00:00:23)
  Creating disk... Finished (00:00:09)
  Attaching disk '7e2f8d2f-fabd-49f5-9980-d13e953ad0f2' to VM '05b15c2f-21d9-41e8-a5a2-b48a6347dcf2'... Finished (00:00:27)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)
```
...but the debug log shows a panic:
```
[registryServer] 2016/04/27 16:36:35 DEBUG - Stopping registry server
[File System] 2016/04/27 16:36:35 DEBUG - Remove all /Users/cpi/.bosh_init/installations/9361ac08-60d1-4fba-74ae-edf586f14fb4/jobs/openstack_cpi
[registryServer] 2016/04/27 16:36:35 DEBUG - Registry error occurred: accept tcp 127.0.0.1:6901: use of closed network connection
[File System] 2016/04/27 16:36:35 DEBUG - Remove all /Users/cpi/.bosh_init/installations/9361ac08-60d1-4fba-74ae-edf586f14fb4/blobs/bb486377-1d5a-47f8-61ff-2b7161e75d37
[File System] 2016/04/27 16:36:35 DEBUG - Remove all /Users/cpi/.bosh_init/installations/9361ac08-60d1-4fba-74ae-edf586f14fb4/tmp/stemcell-manager868205893
[File System] 2016/04/27 16:36:35 DEBUG - Remove all /Users/cpi/.bosh_init/installations/9361ac08-60d1-4fba-74ae-edf586f14fb4/tmp/bosh-init-release390670427
[File System] 2016/04/27 16:36:35 DEBUG - Remove all /Users/cpi/.bosh_init/installations/9361ac08-60d1-4fba-74ae-edf586f14fb4/tmp/bosh-init-release391490046
[Main] 2016/04/27 16:36:36 ERROR - Panic: interface conversion: interface is nil, not string
********************
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/cloudfoundry/bosh-init/internal/github.com/cloudfoundry/bosh-utils/logger.(*logger).HandlePanic(0xc8200df020, 0x652180, 0x4)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/internal/github.com/cloudfoundry/bosh-utils/logger/logger.go:146 +0x128
panic(0x5a49e0, 0xc820301680)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/cloudfoundry/bosh-init/deployment/instance/state.(*builder).defaultAddress(0xc8200fab60, 0xc82022dda0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/deployment/instance/state/builder.go:212 +0x568
github.com/cloudfoundry/bosh-init/deployment/instance/state.(*builder).Build(0xc8200fab60, 0xc8203aeb18, 0x4, 0x0, 0xc8203ae828, 0x4, 0xc8203d7620, 0xc82027f4d0, 0x1, 0x1, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/deployment/instance/state/builder.go:85 +0x999
github.com/cloudfoundry/bosh-init/deployment/instance.(*instance).UpdateJobs(0xc8202a4080, 0xc8203ae828, 0x4, 0xc8203d7620, 0xc82027f4d0, 0x1, 0x1, 0xc8201e4e70, 0x2, 0x2, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/deployment/instance/instance.go:137 +0xb8
github.com/cloudfoundry/bosh-init/deployment.(*deployer).createAllInstances(0xc820098f50, 0xc8203ae828, 0x4, 0xc8203d7620, 0xc82027f4d0, 0x1, 0x1, 0xc8201e4e70, 0x2, 0x2, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/deployment/deployer.go:106 +0xab1
github.com/cloudfoundry/bosh-init/deployment.(*deployer).Deploy(0xc820098f50, 0xaa7a38, 0xc82025dd80, 0xc8203ae828, 0x4, 0xc8203d7620, 0xc82027f4d0, 0x1, 0x1, 0xc8201e4e70, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/deployment/deployer.go:71 +0x205
github.com/cloudfoundry/bosh-init/cmd.(*DeploymentPreparer).deploy.func1(0xa98988, 0xc8201e8320, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:261 +0x5f1
github.com/cloudfoundry/bosh-init/ui.(*stage).PerformComplex(0xc820098cd0, 0x661060, 0x9, 0xc8200fa1c0, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/ui/stage.go:65 +0x44f
github.com/cloudfoundry/bosh-init/cmd.(*DeploymentPreparer).deploy(0xc82010e1e0, 0xaa6830, 0xc82009c580, 0xc82007dec0, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:272 +0xda9
github.com/cloudfoundry/bosh-init/cmd.(*DeploymentPreparer).PrepareDeployment.func4.1(0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:211 +0xeb
github.com/cloudfoundry/bosh-init/installation.(*installation).WithRunningRegistry(0xc82009c580, 0xa98730, 0xc8200df020, 0xa98988, 0xc820098cd0, 0xc8201e8c30, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/installation/installation.go:58 +0x12e
github.com/cloudfoundry/bosh-init/cmd.(*DeploymentPreparer).PrepareDeployment.func4(0xaa6830, 0xc82009c580, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:212 +0x1bd
github.com/cloudfoundry/bosh-init/cpi/release.CpiInstaller.WithInstalledCpiRelease(0xa98ba0, 0xc820074940, 0xa98cb0, 0xc8200a4120, 0x0, 0xc820131650, 0x4, 0xc8201761c0, 0xd, 0xc820174860, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:63 +0x285
github.com/cloudfoundry/bosh-init/cmd.(*DeploymentPreparer).PrepareDeployment(0xc82010e1e0, 0xa98988, 0xc820098cd0, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:213 +0x2118
github.com/cloudfoundry/bosh-init/cmd.(*deployCmd).Run(0xc820076420, 0xa98988, 0xc820098cd0, 0xc82007c0e0, 0x1, 0x1, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deploy_cmd.go:74 +0x8a2
github.com/cloudfoundry/bosh-init/cmd.(*Runner).Run(0xc820325e20, 0xa98988, 0xc820098cd0, 0xc82007c0d0, 0x2, 0x2, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/cmd/runner.go:27 +0x1ab
main.main()
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-init/main.go:46 +0x80c
```

The commit that caused this seems to be https://github.com/cloudfoundry/bosh-init/commit/4dda7bb078f2b4e86590ec104a009af3fc0a3e12#diff-a1745aef0bf1c9f31bb13b6175387bfc because it tries to access the network's IP address from the manifest.
