### ISSUE TITLE
bosh-init uses template name as job name

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh-init#87]
When you define
```
jobs:
- name: myjob
  templates:
  - name: mypackage
    release: release1
```
Then `<%= name %>` in erb template of the mypackage will be `mypackage` instead of `myjob`. For example in case of [collectd](https://github.com/cloudfoundry-community/collectd-boshrelease/blob/9ac68ae21762d9355ce897f470c25539792675b3/jobs/collectd/templates/config/collectd.conf.erb#L13), your VM will send metrics as `collectd` instead of `myjob`. This is quite confusing, especially if you deploy multiple servers with bosh-init and they all end up with same name in their job configs...

bosh-init versions 0.0.95 and 0.0.80 - both have this behaviour.
